version: "3.7"

services:
  database_rentalx:
    image: postgres
    container_name: database_rentalx
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=database_rentalx
      - POSTGRES_PASSWORD=database_rentalx
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
    # network_mode: host
  app:
    build: .
    container_name: rentalx
    ports:
      - "3333:3333"
      - "9229:9229" #Você pode inserir essa porta tbm pra poder usar o debug
    volumes:
      - .:/usr/app
    links:
      - database_rentalx
    depends_on: 
      - database_rentalx

volumes:
  pgdata:
    driver: local